// audit-3 adversarial cases (written independently; mechanisms the builder's matrix does not generate).
// label: 'excluded' (contract: NOT rendered -> must never be verified), 'counted' (contract: rendered -> must be verified),
// 'info' (outside the contract's explicit statements; reported, not graded). pixel:false = pixel oracle not applicable.
import { T, b64 } from './a3-server.mjs';
const fr = (origin, body) => `${origin}/f?b=${b64(body)}`;
const shadow = (id, inner) => `<script>document.getElementById(${JSON.stringify(id)}).attachShadow({mode:'open'}).innerHTML=${JSON.stringify(inner)};</script>`;
const IF = 'width="420" height="70" style="border:0;display:block"';
const IFH = (extra) => `width="420" height="70" style="border:0;${extra}"`;
export const CASES = [
  { id: 'popover-closed', label: 'excluded', html: (t) => `<div popover id="pp">${T(t)}</div>` },
  { id: 'dialog-closed', label: 'excluded', html: (t) => `<dialog>${T(t)}</dialog>` },
  { id: 'details-nested-closed', label: 'excluded', html: (t) => `<details open><summary>s</summary><details><summary>s2</summary><div><span>${T(t)}</span></div></details></details>` },
  { id: 'details-with-shadow-host', label: 'excluded', html: (t) => `<details><summary>s</summary><div id="h"></div></details>${shadow('h', `<p>${T(t)}</p>`)}` },
  { id: 'details-shadow-bare-text', label: 'excluded', html: (t) => `<details><summary>s</summary><div id="h" style="color:#ff00fe;font:bold 34px monospace"></div></details><script>document.getElementById('h').attachShadow({mode:'open'}).append(${JSON.stringify(t)})</script>` },
  { id: 'details-contents-chain', label: 'excluded', html: (t) => `<details><summary>s</summary><div style="display:contents"><span style="display:contents">${T(t)}</span></div></details>` },
  { id: 'details-direct-text-bold', label: 'excluded', html: (t) => `<details style="color:#ff00fe;font:bold 34px monospace"><summary>s</summary>${t}</details>` },
  { id: 'slot-inside-hidden-div', label: 'excluded', html: (t) => `<div id="h">${T(t)}</div>${shadow('h', '<i>x</i><div style="display:none"><slot></slot></div>')}` },
  { id: 'slot-unassigned-name', label: 'excluded', html: (t) => `<div id="h"><span slot="b">${T(t)}</span></div>${shadow('h', '<i>x</i><slot name="a"></slot>')}` },
  { id: 'host-hidden-by-own-style', label: 'excluded', html: (t) => `<div id="h">${T(t)}</div>${shadow('h', '<style>:host{display:none}</style><slot></slot>')}` },
  { id: 'slot-display-none', label: 'excluded', html: (t) => `<div id="h">${T(t)}</div>${shadow('h', '<i>x</i><slot style="display:none"></slot>')}` },
  { id: 'slot-visibility-hidden', label: 'excluded', html: (t) => `<div id="h">${T(t)}</div>${shadow('h', '<i>x</i><div style="visibility:hidden"><slot></slot></div>')}` },
  { id: 'host-content-visibility-hidden', label: 'excluded', html: (t) => `<div id="h" style="content-visibility:hidden;height:50px"></div>${shadow('h', `<p>${T(t)}</p>`)}` },
  { id: 'slot-forward-into-hidden', label: 'excluded', html: (t) => `<div id="o">${T(t)}</div><script>var r=document.getElementById('o').attachShadow({mode:'open'});r.innerHTML='<div id="i"><slot></slot></div>';r.getElementById('i').attachShadow({mode:'open'}).innerHTML='<i>y</i><div hidden><slot></slot></div>';</script>` },
  { id: 'slot-forward-into-closed-details', label: 'excluded', html: (t) => `<div id="o">${T(t)}</div><script>var r=document.getElementById('o').attachShadow({mode:'open'});r.innerHTML='<div id="i"><slot></slot></div>';r.getElementById('i').attachShadow({mode:'open'}).innerHTML='<details><summary>s</summary><slot></slot></details>';</script>` },
  { id: 'contents-chain-in-none', label: 'excluded', html: (t) => `<div style="display:none"><div style="display:contents"><span style="display:contents">${T(t)}</span></div></div>` },
  { id: 'contents-chain-vis-hidden', label: 'excluded', html: (t) => `<div style="visibility:hidden"><div style="display:contents"><div style="display:contents">${T(t)}</div></div></div>` },
  { id: 'hidden-until-found', label: 'excluded', html: (t) => `<div hidden="until-found">${T(t)}</div>` },
  { id: 'svg-defs-text', label: 'excluded', html: (t) => `<svg width="500" height="60"><defs><text id="q" x="0" y="40" fill="#ff00fe" font-size="34" font-weight="bold">${t}</text></defs></svg>` },
  { id: 'svg-text-display-none', label: 'excluded', html: (t) => `<svg width="500" height="60"><text x="0" y="40" display="none" fill="#ff00fe" font-size="34" font-weight="bold">${t}</text></svg>` },
  { id: 'svg-symbol-unused', label: 'excluded', html: (t) => `<svg width="500" height="60"><symbol id="sy"><text x="0" y="40" fill="#ff00fe" font-size="34">${t}</text></symbol></svg>` },
  { id: 'svg-text-visibility-attr', label: 'excluded', html: (t) => `<svg width="500" height="60"><text x="0" y="40" visibility="hidden" fill="#ff00fe" font-size="34" font-weight="bold">${t}</text></svg>` },
  { id: 'canvas-fallback', label: 'excluded', html: (t) => `<canvas width="300" height="50" style="border:1px solid #ccc">${T(t)}</canvas>` },
  { id: 'video-fallback', label: 'excluded', html: (t) => `<video width="300" height="50">${T(t)}</video>` },
  { id: 'noscript', label: 'excluded', html: (t) => `<noscript>${T(t)}</noscript>` },
  { id: 'iframe-tag-fallback-text', label: 'excluded', frames: 1, html: (t) => `<iframe ${IF} srcdoc="<p>x</p>">${t}</iframe>` },
  { id: 'table-row-collapse', label: 'excluded', html: (t) => `<table><tr><td>a</td></tr><tr style="visibility:collapse"><td>${T(t)}</td></tr></table>` },
  { id: 'select-unselected-option', label: 'info', html: (t) => `<select><option>aaa</option><option>${t}</option></select>` },
  { id: 'split-hidden-tail', label: 'excluded', pixel: false, html: (t) => `<p>${t.slice(0, 4)}<span style="display:none">${t.slice(4)}</span></p>` },
  { id: 'split-vishidden-middle', label: 'excluded', pixel: false, html: (t) => `<p>${t.slice(0, 3)}<b style="visibility:hidden">${t.slice(3, 6)}</b>${t.slice(6)}</p>` },
  { id: 'hidden-during-action', label: 'excluded', onclick: "document.getElementById('tp').style.display='none'", html: (t) => `<p id="tp">${T(t)}</p>` },
  { id: 'template-in-shadow', label: 'excluded', html: (t) => `<div id="h"></div>${shadow('h', `<template><p>${t}</p></template><i>x</i>`)}` },
  { id: 'style-text-in-shadow', label: 'excluded', html: (t) => `<div id="h"></div>${shadow('h', `<style>/* ${t} */</style><i>x</i>`)}` },
  { id: 'xo-in-closed-details', label: 'excluded', frames: 1, html: (t, o) => `<details><summary>s</summary><iframe ${IF} src="${fr(o.xo, T(t))}"></iframe></details>` },
  { id: 'xo-in-closed-popover', label: 'excluded', frames: 1, html: (t, o) => `<div popover><iframe ${IF} src="${fr(o.xo, T(t))}"></iframe></div>` },
  { id: 'xo-in-closed-dialog', label: 'excluded', frames: 1, html: (t, o) => `<dialog><iframe ${IF} src="${fr(o.xo, T(t))}"></iframe></dialog>` },
  { id: 'xo-in-hidden-shadow-host', label: 'excluded', frames: 1, html: (t, o) => `<div id="h" style="display:none"></div>${shadow('h', `<iframe ${IF} src="${fr(o.xo, T(t))}"></iframe>`)}` },
  { id: 'xo-slotted-into-hidden-slot', label: 'excluded', frames: 1, html: (t, o) => `<div id="h"><iframe ${IF} src="${fr(o.xo, T(t))}"></iframe></div>${shadow('h', '<i>x</i><div hidden><slot></slot></div>')}` },
  { id: 'xo-until-found-ancestor', label: 'excluded', frames: 1, html: (t, o) => `<div hidden="until-found"><iframe ${IF} src="${fr(o.xo, T(t))}"></iframe></div>` },
  { id: 'xo-nested-inner-vishidden', label: 'excluded', frames: 2, html: (t, o) => `<iframe width="500" height="140" style="border:0" src="${fr(o.xo, `<p>outer</p><iframe ${IFH('visibility:hidden')} src="${fr(o.so, T(t))}"></iframe>`)}"></iframe>` },
  { id: 'xo-nested-inner-in-closed-details', label: 'excluded', frames: 2, html: (t, o) => `<iframe width="500" height="140" style="border:0" src="${fr(o.xo, `<details><summary>s</summary><iframe ${IF} src="${fr(o.so, T(t))}"></iframe></details>`)}"></iframe>` },
  { id: 'xo-nested-3-inner-display-none', label: 'excluded', frames: 3, html: (t, o) => `<iframe width="600" height="220" style="border:0" src="${fr(o.xo, `<iframe width="560" height="180" style="border:0" src="${fr(o.so, `<iframe ${IFH('display:none')} src="${fr(o.xo, T(t))}"></iframe>`)}"></iframe>`)}"></iframe>` },
  { id: 'xo-html-display-none', label: 'excluded', frames: 1, html: (t, o) => `<iframe ${IF} src="${fr(o.xo, `<style>html{display:none}</style>${T(t)}`)}"></iframe>` },
  { id: 'xo-hidden-during-action', label: 'excluded', frames: 1, onclick: "document.getElementById('xf').style.visibility='hidden'", html: (t, o) => `<iframe id="xf" ${IF} src="${fr(o.xo, T(t))}"></iframe>` },
  { id: 'xo-removed-during-action', label: 'excluded', frames: 1, onclick: "document.getElementById('xf').remove()", html: (t, o) => `<iframe id="xf" ${IF} src="${fr(o.xo, T(t))}"></iframe>` },
  { id: 'object-vishidden', label: 'excluded', frames: 1, html: (t, o) => `<object type="text/html" data="${fr(o.xo, T(t))}" width="420" height="70" style="visibility:hidden"></object>` },
  { id: 'xo-zero-size', label: 'excluded', frames: 1, html: (t, o) => `<iframe width="0" height="0" style="border:0" src="${fr(o.xo, T(t))}"></iframe>` },
  { id: 'P-popover-open', label: 'counted', html: (t) => `<div popover="manual" id="pp">${T(t)}</div><script>document.getElementById('pp').showPopover()</script>` },
  { id: 'P-dialog-open', label: 'counted', html: (t) => `<dialog id="dd">${T(t)}</dialog><script>document.getElementById('dd').show()</script>` },
  { id: 'P-details-summary-of-closed', label: 'counted', html: (t) => `<details><summary>${T(t)}</summary>body</details>` },
  { id: 'P-details-open-nested', label: 'counted', html: (t) => `<details open><summary>s</summary><details open><summary>s2</summary><div>${T(t)}</div></details></details>` },
  { id: 'P-contents-host-slot-forward', label: 'counted', html: (t) => `<div id="o" style="display:contents">${T(t)}</div><script>var r=document.getElementById('o').attachShadow({mode:'open'});r.innerHTML='<div id="i" style="display:contents"><slot></slot></div>';r.getElementById('i').attachShadow({mode:'open'}).innerHTML='<div style="display:contents"><slot></slot></div>';</script>` },
  { id: 'P-bare-text-3-shadow-deep', label: 'counted', html: (t) => `<div id="a"></div><script>var r1=document.getElementById('a').attachShadow({mode:'open'});r1.innerHTML='<div id="b"></div>';var r2=r1.getElementById('b').attachShadow({mode:'open'});r2.innerHTML='<div id="c" style="color:#ff00fe;font:bold 34px monospace;display:contents"></div>';r2.getElementById('c').attachShadow({mode:'open'}).append(${JSON.stringify(t)});</script>` },
  { id: 'P-split-5-inline', label: 'counted', html: (t) => `<p style="color:#ff00fe;font:bold 34px monospace">${t.slice(0, 2)}<b>${t.slice(2, 4)}<i>${t.slice(4, 6)}</i></b><a href="#">${t.slice(6, 8)}</a><span style="display:contents">${t.slice(8)}</span></p>` },
  { id: 'P-text-transform', label: 'counted', html: (t) => `<p style="text-transform:uppercase;color:#ff00fe;font:bold 34px monospace">${t.toLowerCase()}</p>` },
  { id: 'P-whitespace', label: 'counted', expect: (t) => `${t.slice(0, 5)} ${t.slice(5)}`, html: (t) => `<p style="color:#ff00fe;font:bold 34px monospace">${t.slice(0, 5)}\n\n    \t ${t.slice(5)}</p>` },
  { id: 'P-svg-text', label: 'counted', html: (t) => `<svg width="600" height="60"><text x="0" y="40" fill="#ff00fe" font-size="34" font-weight="bold">${t}</text></svg>` },
  { id: 'P-deep-1500', label: 'counted', html: (t) => `<div id="dr"></div><script>(function(){var e=document.getElementById('dr');for(var i=0;i<1500;i++){var c=document.createElement('div');e.appendChild(c);e=c;}e.innerHTML=${JSON.stringify(T(t))};})()</script>` },
  { id: 'P-vis-visible-child', label: 'counted', html: (t) => `<div style="visibility:hidden">hidden <span style="visibility:visible">${T(t)}</span></div>` },
  { id: 'P-button-label', label: 'counted', html: (t) => `<button>${T(t)}</button>` },
  { id: 'P-opacity0-counted', label: 'counted', pixel: false, html: (t) => `<p style="opacity:0">${T(t)}</p>` },
  { id: 'P-xo-nested-3-visible', label: 'counted', frames: 3, html: (t, o) => `<iframe width="600" height="220" style="border:0" src="${fr(o.xo, `<iframe width="560" height="180" style="border:0" src="${fr(o.so, `<iframe ${IF} src="${fr(o.xo, T(t))}"></iframe>`)}"></iframe>`)}"></iframe>` },
  { id: 'P-xo-in-open-shadow', label: 'counted', frames: 1, html: (t, o) => `<div id="h"></div>${shadow('h', `<iframe ${IF} src="${fr(o.xo, T(t))}"></iframe>`)}` },
  { id: 'P-xo-in-contents-slot', label: 'counted', frames: 1, html: (t, o) => `<div id="h" style="display:contents"><iframe ${IF} src="${fr(o.xo, T(t))}"></iframe></div>${shadow('h', '<div style="display:contents"><slot></slot></div>')}` },
  { id: 'P-xo-vis-visible-child', label: 'counted', frames: 1, html: (t, o) => `<iframe ${IF} src="${fr(o.xo, `<div style="visibility:hidden">h <span style="visibility:visible">${T(t)}</span></div>`)}"></iframe>` },
  { id: 'P-xo-in-open-popover', label: 'counted', frames: 1, html: (t, o) => `<div popover="manual" id="pp"><iframe ${IF} src="${fr(o.xo, T(t))}"></iframe></div><script>document.getElementById('pp').showPopover()</script>` },
  { id: 'P-shown-during-action', label: 'counted', onclick: "document.getElementById('tp').hidden=false", html: (t) => `<p id="tp" hidden>${T(t)}</p>` },
  { id: 'P-xo-shown-during-action', label: 'counted', frames: 1, onclick: "document.getElementById('xf').style.display='block'", html: (t, o) => `<iframe id="xf" ${IFH('display:none')} src="${fr(o.xo, T(t))}"></iframe>` },
  { id: 'I-flex-items-adjacent', label: 'info', html: (t) => `<div style="display:flex;color:#ff00fe;font:bold 34px monospace"><span>${t.slice(0, 5)}</span><span>${t.slice(5)}</span></div>` },
  { id: 'I-inline-block-split', label: 'info', html: (t) => `<p style="color:#ff00fe;font:bold 34px monospace"><span style="display:inline-block">${t.slice(0, 5)}</span>${t.slice(5)}</p>` },
  { id: 'I-textarea', label: 'info', pixel: false, html: (t) => `<textarea>${t}</textarea>` },
  { id: 'I-case-mismatch', label: 'info', pixel: false, expect: (t) => t.toLowerCase(), html: (t) => `<p>${t}</p>` },
  { id: 'I-hidden-ws-between', label: 'info', pixel: false, expect: (t) => `${t.slice(0, 5)} ${t.slice(5)}`, html: (t) => `<p>${t.slice(0, 5)}<span style="display:none"> </span>${t.slice(5)}</p>` },
  { id: 'C-big-visible-100k', label: 'counted', big: true, html: (t) => `<div id="big"></div><script>(function(){var b=document.getElementById('big'),f=document.createDocumentFragment();for(var i=0;i<100000;i++){var d=document.createElement('span');d.textContent='r'+i+' ';f.appendChild(d);}b.appendChild(f);})()</script><p style="position:fixed;top:0;left:0;background:#fff">${T(t)}</p>` },
  { id: 'C-budget-hidden-only-220k', label: 'excluded', big: true, pixel: false, html: (t) => `<div id="big" style="display:none"></div><script>(function(){var b=document.getElementById('big'),f=document.createDocumentFragment();for(var i=0;i<220000;i++){var d=document.createElement('span');d.textContent=${JSON.stringify(t)};f.appendChild(d);}b.appendChild(f);})()</script>` },
  { id: 'C-budget-hidden-then-visible-220k', label: 'counted-or-unavailable', big: true, pixel: false, html: (t) => `<div id="big" style="display:none"></div><script>(function(){var b=document.getElementById('big'),f=document.createDocumentFragment();for(var i=0;i<220000;i++){var d=document.createElement('span');d.textContent=${JSON.stringify(t)};f.appendChild(d);}b.appendChild(f);})()</script><p>${T(t)}</p>` },
  { id: 'C-huge-no-token-450k', label: 'excluded', big: true, pixel: false, html: () => `<div id="big"></div><script>(function(){var b=document.getElementById('big'),f=document.createDocumentFragment();for(var i=0;i<450000;i++){f.appendChild(document.createTextNode('w'+i+' '));}b.appendChild(f);})()</script>` },
];
