import os from 'node:os'; import path from 'node:path'; import fsp from 'node:fs/promises'; import { pathToFileURL } from 'node:url';
const SPR = 'e:/ai-cache/tmp/claude/e--hmx-projects-internal-projects-pinchtab--claude-worktrees-project-understanding-696041/37c49594-f3f4-44c7-b8d5-a5f569bf406f/scratchpad';
const nrmG = (p) => path.resolve(p).split(path.sep).join('/').toLowerCase().replace(/[/]+$/, '');
if (process.platform !== 'win32' || !nrmG(os.tmpdir()).startsWith(SPR + '/')) { console.error(`PROBE GUARD: tmpdir=${os.tmpdir()} not under scratchpad`); process.exit(97); }
console.error(`[probe-guard] tmpdir=${nrmG(os.tmpdir())} pid=${process.pid}`);
const TP = await import(pathToFileURL(process.env.TP_MODULE).href);
const C = await import(new URL('./common.mjs', import.meta.url).href);
const { P, check, done, tree, sameTree, exists, setOld, profileDir, header, sleep } = C;
import { spawn } from 'node:child_process';
header('win-a6 rule 3 isolated (live dummy owner)');
const ISO = os.tmpdir(); const T = await fsp.mkdtemp(path.join(ISO, 'a6-'));
const dummy = spawn(process.execPath, ['-e', 'setInterval(()=>{},1000)'], { stdio: 'ignore', windowsHide: true }); await sleep(800);
console.log(`INFO dummy pid=${dummy.pid}`);
const d1 = await profileDir(path.join(T, 'sutradhar-cli-1790000000200-AbC123'), { lockfile: false, marker: dummy.pid }); await setOld(d1);
const d2 = await profileDir(path.join(T, 'sutradhar-cli-1790000000201'), { lockfile: false, marker: dummy.pid }); await setOld(d2);
P('dir', d1); P('dir', d2);
const sw = await TP.sweepStaleTempProfiles({ tmpRoot: T, scan: async () => [], minAgeMs: 0 });
for (const k of sw.kept) P('kept', k.dir, `reason=${k.reason}`);
check('A6 sweep: both kept owner-alive', sw.removed.length === 0 && sw.kept.filter((k) => k.reason === 'owner-alive').length === 2, JSON.stringify(sw.kept.map((k) => k.reason)));
const r = await TP.removeSessionTempProfile(d1, undefined, { tmpRoot: T, scan: async () => [], removeTimeoutMs: 500 });
P('close-result', d1, `removed=${r.removed} reason=${r.reason}`);
check('A6 close: owner-alive', r.removed === false && r.reason === 'owner-alive', JSON.stringify(r));
const rw = await TP.removeSessionTempProfile(d1, dummy.pid, { tmpRoot: T, scan: async () => [], exitTimeoutMs: 600 });
check('A6 close with live chromePid: kept (did not exit in time)', rw.removed === false && /did not exit/.test(rw.reason), JSON.stringify(rw));
dummy.kill('SIGKILL'); const t0 = performance.now(); while (performance.now() - t0 < 15000 && TP.isPidAlive(dummy.pid)) await sleep(100);
check('A6 dummy dead (killed by its PID)', !TP.isPidAlive(dummy.pid));
const sw2 = await TP.sweepStaleTempProfiles({ tmpRoot: T, scan: async () => [], minAgeMs: 0 });
for (const x of sw2.removed) P('removed', x);
check('A6 after kill: both removed', sw2.removed.length === 2 && !(await exists(d1)) && !(await exists(d2)), JSON.stringify(sw2.kept));
done();
