#!/bin/bash
export MSYS_NO_PATHCONV=1
ISO="E:/AI-Cache/tmp/claude/E--HMX-Projects-Internal-Projects-PinchTab--claude-worktrees-project-understanding-696041/37c49594-f3f4-44c7-b8d5-a5f569bf406f/scratchpad/r062/S8-tmp"; [ -f "$ISO/.r062" ] || { echo "ISO missing or unmarked"; exit 1; }
cd "E:/AI-Cache/tmp/claude/E--HMX-Projects-Internal-Projects-PinchTab--claude-worktrees-project-understanding-696041/37c49594-f3f4-44c7-b8d5-a5f569bf406f/scratchpad/r062/S8/tree"
run() { label=$1; shift; echo "=== $label $(date +%T)"; env TEMP="$ISO" TMP="$ISO" TMPDIR="$ISO" NODE_OPTIONS="--import=file:///E:/AI-Cache/tmp/claude/E--HMX-Projects-Internal-Projects-PinchTab--claude-worktrees-project-understanding-696041/37c49594-f3f4-44c7-b8d5-a5f569bf406f/scratchpad/iso/assert-tmp.mjs" SUTRADHAR_ISO_QUIET=1 SP="E:/AI-Cache/tmp/claude/E--HMX-Projects-Internal-Projects-PinchTab--claude-worktrees-project-understanding-696041/37c49594-f3f4-44c7-b8d5-a5f569bf406f/scratchpad" WT="E:/AI-Cache/tmp/claude/E--HMX-Projects-Internal-Projects-PinchTab--claude-worktrees-project-understanding-696041/37c49594-f3f4-44c7-b8d5-a5f569bf406f/scratchpad/r062/S8/tree" timeout 3000 node "$@" > "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S8/mutants-$label.txt" 2>&1; echo "rc=$?" >> "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S8/mutants-$label.txt"; grep -E "survivors|SURVIVED|BAD-APPLY|BASELINE|MISMATCH|rc=" "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S8/mutants-$label.txt"; }
run S2 "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S2/run-mutants.mjs"
run S3a "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S3a/run-mutants.mjs"
run S3b "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S3b/run-mutants.mjs"
run S3c "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S3c/run-mutants.mjs"
run S4 "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S4/run-mutants.mjs"
run S5 "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/tools/mutrun.mjs" "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S5/mut-spec.json"
run S6 "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/tools/mutrun.mjs" "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S6/mut-spec.json"
run S7 "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/tools/mutrun.mjs" "E:/HMX_Projects/Internal_Projects/PinchTab/.claude/worktrees/project-understanding-696041/.ai/loop/release-0.6.2/evidence/S7/mut-spec.json"
echo "=== all done $(date +%T)"
