// AUDIT-1: exact eviction counts at the 200 boundary, tab and session views, two tabs (MCP, real Chrome).
import path from 'node:path'; import fs from 'node:fs/promises';
import { here, mcpClient, startServer } from './lib.mjs';
const repo = path.resolve(here, '../../../../../..');
const srv = await startServer();
const c = mcpClient(path.join(repo, 'packages/mcp-server/dist/cli.js'));
const checks = [];
const T = (name, ok, obs) => { checks.push({ name, ok: !!ok, obs }); console.log((ok ? 'PASS ' : 'FAIL ') + name + ' ' + JSON.stringify(obs)); };
try {
  await c.init();
  const sid = (await c.tool('browser.launch', { headless: true, initialUrl: srv.origin + '/p' })).json.sessionId;
  const t1 = (await c.tool('browser.list_tabs', { sessionId: sid })).json;
  const tab1 = (Array.isArray(t1) ? t1 : t1.tabs)[0].id ?? (Array.isArray(t1) ? t1 : t1.tabs)[0].tabId;
  const tab2 = (await c.tool('browser.new_tab', { sessionId: sid, url: srv.origin + '/p2' })).json.id;
  let n1 = 0, n2 = 0;
  const ev = async (tabId, k) => { for (let i = 0; i < k; i++) { const idx = tabId === tab1 ? ++n1 : ++n2; const r = await c.tool('browser.eval', { sessionId: sid, tabId, code: idx + '+0 /*' + (tabId === tab1 ? 't1' : 't2') + '*/' }); if (r.isError) throw new Error(r.text); } };
  const H = async (args) => (await c.tool('browser.get_action_history', { sessionId: sid, ...args })).json;
  await ev(tab1, 199);
  let a = await H({ tabId: tab1 }), s = await H({ scope: 'session' });
  T('tab1 199: len 199, evicted 0, no note', a.entries.length === 199 && a.evicted === 0 && !('note' in a), [a.entries.length, a.evicted, a.note]);
  T('session 199: evicted 0', s.entries.length === 199 && s.evicted === 0 && !('note' in s), [s.entries.length, s.evicted]);
  await ev(tab2, 1);
  s = await H({ scope: 'session' });
  T('session exactly 200: evicted 0, no note', s.entries.length === 200 && s.evicted === 0 && !('note' in s), [s.entries.length, s.evicted, s.note]);
  await ev(tab2, 1);
  s = await H({ scope: 'session' }); a = await H({ tabId: tab1 }); const b = await H({ tabId: tab2 });
  T('session 201: evicted 1, singular note, [0].seq 2', s.entries.length === 200 && s.evicted === 1 && s.note === '1 older entry was evicted — only the most recent 200 are kept.' && s.entries[0].seq === 2, [s.evicted, s.note, s.entries[0].seq]);
  T('tab1 unaffected 199/0; tab2 2/0', a.entries.length === 199 && a.evicted === 0 && b.entries.length === 2 && b.evicted === 0, [a.entries.length, a.evicted, b.entries.length, b.evicted]);
  await ev(tab1, 1);
  a = await H({ tabId: tab1 }); s = await H({ scope: 'session' });
  T('tab1 exactly 200: evicted 0, no note', a.entries.length === 200 && a.evicted === 0 && !('note' in a), [a.entries.length, a.evicted]);
  T('session 202: evicted 2', s.evicted === 2 && s.entries[0].seq === 3, [s.evicted, s.entries[0].seq]);
  await ev(tab1, 1);
  a = await H({ tabId: tab1 });
  T('tab1 201: evicted 1, singular note, oldest is eval #2', a.entries.length === 200 && a.evicted === 1 && /^1 older entry was evicted/.test(a.note ?? '') && a.entries[0].target === '2+0 /*t1*/', [a.evicted, a.note, a.entries[0].target]);
  await ev(tab1, 5);
  a = await H({}); s = await H({ scope: 'session' });
  T('default (active tab = tab1?) 206: evicted 6, plural note, oldest #7', a.tabId === tab1 && a.evicted === 6 && a.note === '6 older entries were evicted — only the most recent 200 are kept.' && a.entries[0].target === '7+0 /*t1*/', [a.tabId === tab1, a.evicted, a.note, a.entries[0].target]);
  T('session 208: evicted 8, [0].seq 9, seq contiguous', s.evicted === 8 && s.entries[0].seq === 9 && s.entries.every((e, i) => e.seq === 9 + i), [s.evicted, s.entries[0].seq, s.entries.at(-1).seq]);
  await c.tool('browser.close_tab', { sessionId: sid, tabId: tab2 });
  s = await H({ scope: 'session' });
  const closedEntries = s.entries.filter((e) => e.tabId === tab2).length;
  T('after close_tab(tab2): session still 200/8 and holds tab2 entries', s.entries.length === 200 && s.evicted === 8 && closedEntries === 2, [s.entries.length, s.evicted, closedEntries]);
  const t2v = await c.tool('browser.get_action_history', { sessionId: sid, tabId: tab2 });
  T('tab view of closed tab is an error', t2v.isError, t2v.text.slice(0, 100));
  const bad = await c.tool('browser.get_action_history', { sessionId: sid, scope: 'session', tabId: tab1 });
  T('scope session + tabId rejected', bad.isError && /cannot be combined/.test(bad.text), bad.text.slice(0, 120));
  await c.tool('browser.shutdown_all', {});
} finally { c.kill(); await srv.close(); await fs.writeFile(path.join(here, 'eviction.json'), JSON.stringify(checks, null, 1)); }
