const fs = require('fs');
const p = '.ai/loop/field-report-2/gaps.md';
let c = fs.readFileSync(p, 'utf8');
const crlf = c.includes('\r\n');
c = c.replace(/\r\n/g, '\n');
const used = [...c.matchAll(/\| GAP-(\d+) /g)].map((m) => Number(m[1]));
let next = Math.max(...used) + 1;
const S = '0.6.2 S10b';
const rows = [
  [`${S} (plan S10b 1, plan 2.4)`, 'minor, behaviour', 'I-051 covers only the "no state" case. Self-heal (a `state.json` exists but its browser is gone) still starts a fresh blank session for a non-launch verb such as `text`, announced on stderr. A script that runs a read verb after the browser died therefore still sees an empty page with exit 0 apart from the stderr line. Decide whether self-heal should also fail for non-launch verbs (it interacts with the 0.7.0 close/recovery redesign, GAP-398).', 'OPEN (deferred, with GAP-398)'],
  [`${S} (plan S10b 2)`, 'minor, unverifiable here', '`packages/agent/src/core/agent-loop.ts:705` still cuts the page observation `raw.slice(0, 2000)` for `agent.runGoal` (labelled an "excerpt"). Not changed by 0.6.2 (the host-AI path is the supported one); it needs an LLM provider to verify, which this environment does not have.', 'OPEN'],
  [`${S} (plan S10b 3)`, 'minor', '`apps/server/src/routes/browser-routes.ts:299` returns the REST snapshot text `.slice(0, 1500)` with no truncation marker and no total (the same silent-cut class as PROB-048, on the dashboard/REST surface). Not changed by 0.6.2.', 'OPEN'],
  [`${S} (plan S10b 4, S4)`, 'minor, silent degradation', '`buildGraph`\'s outer catch-all in `packages/browser/src/dom/dom-semantic-engine.ts` returns an EMPTY graph silently on any unexpected error (the detached-frame trigger is fixed by `frameCall`, but any other throw still yields "Interactive elements (0)" with no reason). Recommended: report the error (a `skippedFrames`-style note or a thrown error) instead of an empty graph.', 'OPEN'],
  [`${S} (plan S10b 5, PROB-050)`, 'info, cosmetic', '`sutradhar eval` of a void expression (for example `history.back()`) still prints the literal `undefined`; 0.6.2 added `back`/`forward`/`reload` but did not change `eval` output.', 'OPEN'],
  [`${S} (plan S10b 6, S4 step 6)`, 'info, external', 'On kayak.com, `nav https://www.kayak.com/stays --settle` ended with `Fatal: net::ERR_ABORTED` in the S4 supporting run (a navigation abort, not a frame error), so the stays scenario of WebBench 2561 could not be reproduced end to end. Not an I-047 finding; may be site-side (redirect/anti-automation). Re-checked in S11b (see `release-0.6.2/evidence/S11b`).', 'OPEN (unconfirmed, external)'],
  [`${S} (plan S10b 7, WebBench 2388)`, 'unconfirmed', 'From `.ai/loop/webbench-2026-10-04/CANDIDATE-FIXES.md` items 2 and 3, neither reproduced: (a) a click that opens a new tab makes `--expect-url-changed` exit 4 because the check reads the ORIGINAL tab; (b) a "Past 24 hours" click reported a 15 s timeout although the filter applied.', 'OPEN (unconfirmed)'],
  [`${S} (plan S10b 8, S11 item 6)`, 'minor, pre-existing', 'SDK types for consumers: the published `dist/*.d.ts` re-export from `@sutradhar/capability-runtime`, which is not on npm, so `PageTextResult` and other runtime types resolve to `any` for a consumer of `sutradhar`. Pre-dates 0.6.2 (new types such as `PageTextResult` inherit it). The S11 consumer type probe records the observed result (`release-0.6.2/evidence/S11`).', 'OPEN'],
  [`${S} (Addendum A.1, PROB-052)`, 'medium, pre-existing', 'PDF text extraction fails in every BUNDLED build (CLI, SDK, MCP): pdf.js is inlined and needs the optional native module `@napi-rs/canvas` (DOMMatrix/ImageData/Path2D) at run time, which `packages/sutradhar` does not ship. 0.6.2 reports it (exit 1 / `isError` / `PageTextReadError` naming PROB-052) instead of empty text. Fix options: (1) add `@napi-rs/canvas` as a dependency of `sutradhar` (native, per-platform binaries, install size and platform-matrix cost); (2) bundle a pure-JS `DOMMatrix`/`ImageData`/`Path2D` polyfill ahead of pdf.js (text only needs the matrix maths), or load `pdfjs-dist`\'s legacy build with its own polyfills. Either needs a release decision plus a live PDF check on the bundled build (SP-2 showed headless works).', 'OPEN (PROB-052)'],
  [`${S} (S8 A-3, S4 deviation 6)`, 'minor, pre-existing', 'Navigation hang: on the churn page, a second `goto()`/`nav` to the page after a `click` hangs until Chrome\'s 30 s navigation timeout (`TimeoutError: Navigation timeout of 30000 ms exceeded`) on the published 0.6.1 AND on HEAD. It makes the `live-detach.mjs` L2 level abort FATAL on a flaky run (seen against NEG061 in the S8 audit); the harness workaround is `LEVELS=L1,L3,L4`. Unrelated to frame detach; root cause not investigated.', 'OPEN'],
  [`${S} (S8 A-4)`, 'minor, pre-existing', 'Clicking an element inside a child frame that is navigating cross-origin surfaces raw Puppeteer texts (`Execution context was destroyed`, `Argument should belong to the same JavaScript world as target object`) on HEAD and on 0.6.1; never "detached Frame". The "navigated away" diagnosis that exists for the main frame is not applied to child frames.', 'OPEN'],
  [`${S} (S8 A-2)`, 'info, evidence', 'The committed I-047 inventory (`release-0.6.2/evidence/S4/frame-call-sites.md`) is keyed at the S4 commit; S7 shifted 16 sites by pure line deltas (9 in `post-conditions.ts`, 22 in `cli.ts`), so `check-inventory` on a later tree reports MISSING/EXTRA until it is re-keyed (the S11 gate re-keys it on HEAD).', 'OPEN (re-keyed in S11 evidence)'],
  [`${S} (S8 A-5)`, 'info, coverage', 'The builder harness H1-SPA covers `pushState` entries only (fixture commit 6c952b8 replaced the load-time `location.hash` assignment, which Chrome turns into a replace). Post-load `location.hash` entries are covered only by the auditor\'s probe P4 (S8 audit.md), not by a committed harness.', 'OPEN'],
  [`${S} (S8 A-7)`, 'info, test discrimination', 'The live S3a(j) check (alert open, then `text`) exits 3 (dialog guard) on both 0.6.1 and HEAD, so it does not discriminate; the DOM read-failure path of `text` is covered by unit tests only (M-048p/q/r/s). The PDF read failure (A.1) is the live discriminating proof.', 'OPEN'],
  [`${S} (S8 A-9, A-10)`, 'info, documentation', 'A-9: the DOM text path makes two in-page evaluates (the pre-existing `contentType` PDF probe, then the window), not one; only the window crosses CDP. A-10: the S5 README attributes the M-049a kill also to `selector-args.spec.ts`, but the CLI suite resolves `@sutradhar/capability-runtime` through its built dist, so a source mutant of `types.ts` is killed by `runtime.spec.ts` alone.', 'OPEN (accepted)'],
];
const first = next;
let out = '';
for (const r of rows) out += `| GAP-${next++} | ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} | - |\n`;
c = c.replace(/\n*$/, '\n') + out;
if (crlf) c = c.replace(/\n/g, '\r\n');
fs.writeFileSync(p, c);
console.log(`appended ${rows.length} rows GAP-${first}..GAP-${next - 1}; crlf=${crlf}`);
