// GENERATED by gen-audit-defs.mjs from the auditors' mutant lists (unchanged find/replace text).
export const MUTANTS = {
 "A1": {
  "desc": "audit-1 A1: MCP only: config allowedDomains outranks env (one pair reversed on one surface)",
  "file": "packages/mcp-server/src/server.ts",
  "pkg": "mcp-server",
  "find": "resolveAllowedDomains({ option: options.allowedDomains, env: process.env, config: cfg })",
  "replace": "resolveAllowedDomains({ option: options.allowedDomains ?? cfg?.values.allowedDomains, env: process.env, config: cfg })"
 },
 "A2": {
  "desc": "audit-1 A2: CLI only: sticky state dialog outranks an accept/dismiss flag",
  "file": "packages/cli/src/dialog-cli.ts",
  "pkg": "cli",
  "find": "if (dialogFlag === 'accept' || dialogFlag === 'dismiss') {",
  "replace": "if ((dialogFlag === 'accept' || dialogFlag === 'dismiss') && !state?.dialogPolicy) {"
 },
 "A3": {
  "desc": "audit-1 A3: .git exclusion computed on the literal (non-canonical) path: junction-to-.git bypass",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "const rel = c.slice(base.length)",
  "replace": "const rel = d.abs.slice(baseDir.length)"
 },
 "A4": {
  "desc": "audit-1 A4: .git exclusion dropped entirely",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "if (rel.some((s) => foldAscii(s) === '.git')) {",
  "replace": "if (false && rel.some((s) => foldAscii(s) === '.git')) {"
 },
 "A5": {
  "desc": "audit-1 A5: a discovered file is treated like an explicit (trusted) one",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "    origin = 'discovered';",
  "replace": "    origin = 'env';"
 },
 "A6": {
  "desc": "audit-1 A6: an explicit falsy value (0) falls through instead of winning",
  "file": "packages/capability-runtime/src/config-precedence.ts",
  "pkg": "capability-runtime",
  "find": "    if (value === undefined) continue;",
  "replace": "    if (!value) continue;"
 },
 "A7": {
  "desc": "audit-1 A7: CLI fail-open: --allowlist-domains \"\" / \" , \" means unrestricted again",
  "file": "packages/cli/src/parse-args.ts",
  "pkg": "cli",
  "find": "allowlistDomainsFlagIndex !== -1 && !allowlistDomainsFlag?.length",
  "replace": "allowlistDomainsFlagIndex !== -1 && allowlistDomainsRaw === undefined"
 },
 "A8": {
  "desc": "audit-1 A8: home boundary compared literally (no canonicalisation/case fold)",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "if (sameFold(here, home)) return",
  "replace": "if (dir === homedir) return"
 },
 "A9": {
  "desc": "audit-1 A9: MCP: server default viewport outranks the browser.launch call argument",
  "file": "packages/mcp-server/src/tools.ts",
  "pkg": "mcp-server",
  "find": "const vp = viewport ?? options.defaultViewport;",
  "replace": "const vp = options.defaultViewport ?? viewport;"
 },
 "A10": {
  "desc": "audit-1 A10: duplicate keys only detected at the top level",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "if (top && top.obj && top.expectKey) {",
  "replace": "if (top && top.obj && top.expectKey && stack.length === 1) {"
 },
 "A11": {
  "desc": "audit-1 A11: SDK: a config dialog \"report\" is not mapped to auto (would hang page.evaluate)",
  "file": "packages/capability-runtime/src/config-precedence.ts",
  "pkg": "capability-runtime",
  "find": "if (r.source === 'config' && i.surface === 'sdk' && r.value?.mode === 'report') {",
  "replace": "if (false && r.source === 'config' && i.surface === 'sdk' && r.value?.mode === 'report') {"
 },
 "A12": {
  "desc": "audit-1 A12: nested unknown keys (dialog.*) silently dropped without a warning",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "warnUnknown('dialog.', k, DIALOG_KEYS);",
  "replace": "void k;"
 },
 "A5b": {
  "desc": "audit-1 A5b: a discovered file is treated like an explicit (trusted) one (type-valid spelling)",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "    origin = 'discovered';",
  "replace": "    origin = ['env', 'discovered'][0] as ConfigOrigin;"
 },
 "A8b": {
  "desc": "audit-1 A8b: home boundary needs a LITERAL match of the cwd walk to the home string (no canonical/case-fold equality)",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "if (sameFold(here, home)) return",
  "replace": "if (sameFold(here, home) && dir === homedir) return"
 },
 "B1": {
  "desc": "audit-2 B1: set-but-unusable env (blank/\";;\") counts as \"env set\": refusal skipped and the FILE roots used",
  "file": "packages/capability-runtime/src/fs-roots.ts",
  "pkg": "capability-runtime",
  "find": "    if (envResult.roots) {\n      allowedDownloadRoots = envResult.roots;\n      downloadSource = 'env';",
  "replace": "    if (envResult.roots || (input.env !== undefined && input.env[DOWNLOAD_ROOTS_ENV] !== undefined && !!input.config?.allowedDownloadRoots?.length)) {\n      allowedDownloadRoots = envResult.roots ?? input.config!.allowedDownloadRoots!.map((r) => path.resolve(input.config!.baseDir, r));\n      downloadSource = 'env';"
 },
 "B2": {
  "desc": "audit-2 B2: env set: env roots MERGED with the refused file roots",
  "file": "packages/capability-runtime/src/fs-roots.ts",
  "pkg": "capability-runtime",
  "find": "      allowedDownloadRoots = envResult.roots;\n",
  "replace": "      allowedDownloadRoots = [...envResult.roots, ...(input.config?.allowedDownloadRoots ?? [])];\n"
 },
 "B3": {
  "desc": "audit-2 B3: an allowedDownloadRoots option that is present but empty/null skips the refusal (file roots used)",
  "file": "packages/capability-runtime/src/fs-roots.ts",
  "pkg": "capability-runtime",
  "find": "      if (input.config.downloadRefusal !== undefined) {",
  "replace": "      if (input.config.downloadRefusal !== undefined && input.options?.allowedDownloadRoots === undefined) {"
 },
 "B4": {
  "desc": "audit-2 B4: MCP only: refusal not passed to the resolver (pre-fix composition)",
  "file": "packages/mcp-server/src/server.ts",
  "pkg": "mcp-server",
  "find": "      config: fsRootsConfigLayer(cfg),",
  "replace": "      config: fsRootsConfigLayer(cfg ? { ...cfg, downloadRefusal: undefined } : cfg),"
 },
 "B5": {
  "desc": "audit-2 B5: SDK only: refusal not passed to the resolver",
  "file": "packages/sutradhar/src/index.ts",
  "pkg": "sutradhar",
  "find": "    config: fsRootsConfigLayer(cfg),",
  "replace": "    config: fsRootsConfigLayer(cfg ? { ...cfg, downloadRefusal: undefined } : cfg),"
 },
 "B6": {
  "desc": "audit-2 B6: CLI resolver: download <dir> is NOT treated as a higher layer (refusal still raised)",
  "file": "packages/cli/src/project-config-cli.ts",
  "pkg": "cli",
  "find": "i.config && i.extraDownloadRoots?.length && i.config.downloadRefusal !== undefined",
  "replace": "i.config && i.extraDownloadRoots?.length === -1 && i.config.downloadRefusal !== undefined"
 },
 "B7": {
  "desc": "audit-2 B7: CLI resolver: download <dir> clears the refusal but KEEPS the file roots (merged with <dir>)",
  "file": "packages/cli/src/project-config-cli.ts",
  "pkg": "cli",
  "find": "? { ...i.config, resolved: { ...i.config.resolved, allowedDownloadRoots: undefined }, downloadRefusal: undefined }",
  "replace": "? { ...i.config, downloadRefusal: undefined }"
 },
 "B8": {
  "desc": "audit-2 B8: central: fsRootsConfigLayer drops downloadRefusal on every surface",
  "file": "packages/capability-runtime/src/config-precedence.ts",
  "pkg": "capability-runtime",
  "find": "...(cfg.downloadRefusal !== undefined ? { downloadRefusal: cfg.downloadRefusal } : {}) };",
  "replace": "...({} as { downloadRefusal?: string }) };"
 },
 "B9": {
  "desc": "audit-2 B9: over-refusal: an EXPLICIT (SUTRADHAR_CONFIG) file is also refused",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "  if (origin === 'discovered') {\n    let base: string;",
  "replace": "  if (origin === 'discovered' || origin === 'env') {\n    let base: string;"
 },
 "B10": {
  "desc": "audit-2 B10: an UPLOAD-roots env var skips the DOWNLOAD refusal",
  "file": "packages/capability-runtime/src/fs-roots.ts",
  "pkg": "capability-runtime",
  "find": "      if (input.config.downloadRefusal !== undefined) {",
  "replace": "      if (input.config.downloadRefusal !== undefined && input.env?.[UPLOAD_ROOTS_ENV] === undefined) {"
 },
 "B11": {
  "desc": "audit-2 B11: CLI entry (cli.ts): withSession does not hand <dir> to the resolver (download <dir> not a higher layer, real CLI only)",
  "file": "packages/cli/src/cli.ts",
  "pkg": "cli",
  "find": "      extraDownloadRoots: opts?.extraDownloadRoots,\n",
  "replace": ""
 },
 "B12": {
  "desc": "audit-2 B12: blank env becomes \"default roots\": refusal skipped by a set-but-empty env (roots not the file's)",
  "file": "packages/capability-runtime/src/fs-roots.ts",
  "pkg": "capability-runtime",
  "find": "  if (entries.length === 0) return { roots: undefined, warnings };",
  "replace": "  if (entries.length === 0) return { roots: raw.length > 0 ? [defaultDownloadRoot()] : undefined, warnings };"
 },
 "B13": {
  "desc": "audit-2 B13: F7 re-check: home boundary by exact string equality of canonical paths (A8 re-spelled, type-valid)",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "      if (sameFold(here, home)) return { searched, stoppedAt: 'home', stopDir: dir };",
  "replace": "      if (sameFold(here, home) && here === home) return { searched, stoppedAt: 'home', stopDir: dir };"
 },
 "B14": {
  "desc": "audit-2 B14: F3 re-check: inHome from the canonical cwd only (pre-fix)",
  "file": "packages/capability-runtime/src/project-config.ts",
  "pkg": "capability-runtime",
  "find": "inHome = isPathWithinRoot(await canonicalizePath(dir), home, platform) || isPathWithinRoot(dir, literalHome, platform);",
  "replace": "inHome = isPathWithinRoot(await canonicalizePath(dir), home, platform) || (isPathWithinRoot(dir, literalHome, platform) && dir.length < 0);"
 }
};
